spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: dd-MM-yyyy

  profiles:
    active: dev

springdoc:
  api-docs:
    path: /api/docs/api-docs
  swagger-ui:
    path: /api/docs

server:
  port: 8080
  forward-headers-strategy: framework